### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by iT-Boyer** [everblogjs/everblog#10]
```
sync function showConfig () {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by iT-Boyer** [comment]
升级node
node有一个专门管理node.js的版本工具模块`n`
首先安装n模块：`npm install -g n `
 升级node.js到最新稳定版
```
n stable 
```
